name: Automatically build and publish this plugin

on:
  push:
    branches:
      - 'master'

jobs:

  build-and-publish-plugin:
    runs-on: ubuntu-latest
    name: Build and publish plugin
    steps:

    # Execute plugin repo gen action
    - name: Build and publish plugin
      uses: Josh5/action-build-and-publish-unmanic-plugin@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  generate-pr-in-official-repo:
    runs-on: ubuntu-latest
    name: Generate PR for official repo
    permissions:
      contents: write
      actions: write
      pull-requests: write
    steps:

    # Execute PR generation action
    - name: Generate PR for official repo
      uses: Josh5/action-open-pr-in-official-unmanic-repo@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
